apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable?ref=369170275a8ab7f0cd5c08c2eb46b2e641dfefbe # v1.61.1

patches:
  - path: controller-patch.yaml
  - path: node-args-patch.yaml
  - path: node-liveness-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: ebs-external-provisioner-role
    path: ebs-external-provisioner-role-patch.yaml
