---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: "v1.11.3"
  name: prometheus-pushgateway
automountServiceAccountToken: true
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: "v1.11.3"
  name: prometheus-pushgateway
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-pushgateway
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: "v1.11.3"
  name: prometheus-pushgateway-shared
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-pushgateway
        app.kubernetes.io/version: "v1.11.3"
    spec:
      serviceAccountName: prometheus-pushgateway
      automountServiceAccountToken: true
      containers:
        - name: pushgateway
          image: quay.io/prometheus/pushgateway:v1.11.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
          args:
            - --log.level=warn
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          emptyDir: {}
