apiVersion: policies.kyverno.io/v1beta1
kind: MutatingPolicy
metadata:
  name: inject-vault-sidecar-aws-fail-open
  annotations:
    policies.kyverno.io/title: Inject Sidecar - AWS (Fail Open)
spec:
  autogen:
    mutatingAdmissionPolicy:
      enabled: false
  evaluation:
    mutateExisting:
      enabled: true

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]

  matchConditions:
    - name: match-aws-fail-open-annotation
      expression: >-
        object.metadata.?annotations['uw.systems/kyverno-inject-sidecar-request'].orValue('') == 'vault-sidecar-aws-fail-open'

  variables:
    - name: vkac_env
      expression: "'test-env'"
    - name: pod_namespace
      expression: "object.metadata.?namespace.orValue('default')"
    - name: pod_sa
      expression: "object.spec.?serviceAccountName.orValue('default')"

    - name: sidecar_payload
      expression: >-
        yaml.parse(
          '''
          name: vault-credentials-agent
          image: quay.io/utilitywarehouse/vault-kube-cloud-credentials:v0.9.6
          restartPolicy: Always
          args:
            - sidecar
            - -vault-role=''' + variables.vkac_env + '''_aws_''' + variables.pod_namespace + '''_''' + variables.pod_sa + '''
          env:
            - name: VAULT_CAURL
              value: "http://vault-ca-cert.sys-vault:8100"
            - name: VAULT_ADDR
              value: "https://vault.sys-vault:8200"
          ports:
            - name: metrics
              containerPort: 8099
              protocol: TCP
          resources:
            requests:
              cpu: 0m
              memory: 25Mi
            limits:
              cpu: 1000m
              memory: 100Mi
          '''
        )

  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          Object{
            metadata: Object.metadata{
              annotations: { "uw.systems/kyverno-inject-sidecar-status": "injected" }
            },
            spec: Object.spec{
              initContainers: has(object.spec.initContainers) ?
                object.spec.initContainers.map(c,
                  Object.spec.initContainers{
                    name: c.name,
                    env: [ 
                      Object.spec.initContainers.env{ name: "AWS_CONTAINER_CREDENTIALS_FULL_URI",value: "http://127.0.0.1:8098/credentials" }
                    ]
                  }
                ) : [],
              containers: has(object.spec.containers) ?
                object.spec.containers.map(c,
                  Object.spec.containers{
                    name: c.name,
                    env: [ 
                      Object.spec.containers.env{ name: "AWS_CONTAINER_CREDENTIALS_FULL_URI",value: "http://127.0.0.1:8098/credentials" }
                    ]
                  }
                ) : []
            }
          }

    - patchType: JSONPatch
      jsonPatch:
        expression: >-
          size(object.spec.?initContainers.orValue([])) > 0
            ? [JSONPatch{op: "add", path: "/spec/initContainers/-", value: variables.sidecar_payload}]
            : [JSONPatch{op: "add", path: "/spec/initContainers", value: [variables.sidecar_payload]}]
