apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../deploy

  # install CRDs required for testing
  # pre-installing crds saves time in terms of cache update
  - certificates-crd.yaml
  - ../../argocd/cluster
  - ../../traefik/cluster/crds/traefik/crds

patches:
  - path: kyverno-admission-controller-patch.yaml
