apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: onepassword-connect
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
