githubConfigUrl: "https://github.com/utilitywarehouse"

githubConfigSecret: arc-auth

minRunners: 1

containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 50Gi

template:
  spec:
    # https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors#error-access-to-the-path-homerunner_work_tool-is-denied
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        # image of the self hosted runners is different than the base image of GH's cloud runner
        # install common dependencies. git, curl and jq is pre-installed in the image
        command:
          - /bin/bash
          - -c
          - |
            sudo apt-get update
            # build-essential (gcc/g++/make) and python3 are required by node-gyp
            # to compile native node modules when no prebuilt binary is available
            sudo apt-get -y install build-essential python3 gettext-base
            /home/runner/run.sh
        env:
          # Avoid forcing jobs to have a `container` section
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"

controllerServiceAccount:
  namespace: sys-actions
  name: arc-gha-rs-controller

listenerTemplate:
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "8080"
      prometheus.io/scrape: "true"

# copied from upstream helm chart values
# https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml#L149
listenerMetrics:
  counters:
    gha_started_jobs_total:
      labels:
        [
          "repository",
          "organization",
          "enterprise",
          "job_name",
          "event_name",
          "job_workflow_ref",
          "job_workflow_name",
          "job_workflow_target",
        ]
    gha_completed_jobs_total:
      labels:
        [
          "repository",
          "organization",
          "enterprise",
          "job_name",
          "event_name",
          "job_result",
          "job_workflow_ref",
          "job_workflow_name",
          "job_workflow_target",
        ]
  gauges:
    gha_assigned_jobs:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_running_jobs:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_registered_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_busy_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_min_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_max_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_desired_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
    gha_idle_runners:
      labels: ["name", "namespace", "repository", "organization", "enterprise"]
  histograms:
    gha_job_startup_duration_seconds:
      labels:
        [
          "repository",
          "organization",
          "enterprise",
          "job_name",
          "event_name",
          "job_workflow_ref",
          "job_workflow_name",
          "job_workflow_target",
        ]
      buckets:
        [
          0.01,
          0.05,
          0.1,
          0.5,
          1.0,
          2.0,
          3.0,
          4.0,
          5.0,
          6.0,
          7.0,
          8.0,
          9.0,
          10.0,
          12.0,
          15.0,
          18.0,
          20.0,
          25.0,
          30.0,
          40.0,
          50.0,
          60.0,
          70.0,
          80.0,
          90.0,
          100.0,
          110.0,
          120.0,
          150.0,
          180.0,
          210.0,
          240.0,
          300.0,
          360.0,
          420.0,
          480.0,
          540.0,
          600.0,
          900.0,
          1200.0,
          1800.0,
          2400.0,
          3000.0,
          3600.0,
        ]
    gha_job_execution_duration_seconds:
      labels:
        [
          "repository",
          "organization",
          "enterprise",
          "job_name",
          "event_name",
          "job_result",
          "job_workflow_ref",
          "job_workflow_name",
          "job_workflow_target",
        ]
      buckets:
        [
          0.01,
          0.05,
          0.1,
          0.5,
          1.0,
          2.0,
          3.0,
          4.0,
          5.0,
          6.0,
          7.0,
          8.0,
          9.0,
          10.0,
          12.0,
          15.0,
          18.0,
          20.0,
          25.0,
          30.0,
          40.0,
          50.0,
          60.0,
          70.0,
          80.0,
          90.0,
          100.0,
          110.0,
          120.0,
          150.0,
          180.0,
          210.0,
          240.0,
          300.0,
          360.0,
          420.0,
          480.0,
          540.0,
          600.0,
          900.0,
          1200.0,
          1800.0,
          2400.0,
          3000.0,
          3600.0,
        ]
