apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mcp-kube-deployment.yaml

configMapGenerator:
  - name: mcp-kube-config
    files:
      - config.toml=kubernetes-mcp-server-config.toml
      - fetch-ca.sh=fetch-ca.sh
