#!/bin/sh

FALCO_CHART_VERSION="7.0.1"
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
# Generate manifests but delete dummy Secrets. We should create them downstream
# and use strongbox to encrypt.
helm template falco -n sys-falco \
  --set driver.kind=ebpf \
  --set tty=true falcosecurity/falco \
  --set falco.json_output=true \
  --version=${FALCO_CHART_VERSION} \
  --set falcosidekick.enabled=false |\
  awk  'BEGIN{RS="---\n"; ORS="---\n"} !match($0, /kind: Secret\nmetadata/) {print}'> upstream.yaml
