#!/bin/sh

FALCO_CHART_VERSION="8.0.0"
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
# Generate manifests but delete dummy Secrets. We should create them downstream
# and use strongbox to encrypt.
helm template falco -n sys-falco \
  --version=${FALCO_CHART_VERSION} \
  -f values.yaml \
  falcosecurity/falco |\
  awk  'BEGIN{RS="---\n"; ORS="---\n"} !match($0, /kind: Secret\nmetadata/) {print}'> upstream.yaml
