apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream.yaml
  - secret.yaml

patches:
  - path: operator-patch.yaml
  # --set operator.clusterRoleBinding.create=false doesnt work
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: DOES NOT MATTER
    target:
      kind: ClusterRoleBinding
