apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: onepassword-connect
          args:
            - --zap-log-level=info
            - --metrics-secure=false
