apiVersion: apps/v1
kind: Deployment
metadata:
  name: onepassword-connect-operator
spec:
  template:
    spec:
      containers:
        - name: onepassword-connect
          env:
            # watch NS where its deployed
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
