# create empty OnePasswordItem & secret so that kustomize can patch suffix name
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: connect-access-token
spec:
  itemPath:
---
apiVersion: v1
kind: Secret
metadata:
  name: connect-access-token
data:
