apiVersion: policies.kyverno.io/v1
kind: MutatingPolicy
metadata:
  name: enforce-user-namespaces
spec:
  autogen:
    mutatingAdmissionPolicy:
      enabled: false
    podControllers:
      controllers: []

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]

    namespaceSelector:
      matchLabels:
        uw.systems/owner: system

  matchConditions:
    # https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/#limitations
    - name: exclude-host-namespaces
      expression: >-
        !(
          object.spec.?hostNetwork.orValue(false) ||
          object.spec.?hostPID.orValue(false) ||
          object.spec.?hostIPC.orValue(false)
        )
    # Exluding aws-ebs-csi-drive because of 'failed to set MOUNT_ATTR_IDMAP on /dev: invalid
    # argument (maybe the filesystem used doesn't support idmap mounts on this kernel?)'
    - name: exclude-aws-ebs-csi-driver
      expression: >
        !(
          object.metadata.namespace == "kube-system" &&
          object.metadata.labels["app.kubernetes.io/name"] == "aws-ebs-csi-driver"
        )

  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >-
          Object{
            spec: Object.spec{
              hostUsers: false
            }
          }
