#!/bin/sh

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm template prometheus-pushgateway prometheus-pushgateway --repo https://prometheus-community.github.io/helm-charts --version "${VERSION}" \
  > upstream/pushgateway.yaml
