apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onepassword-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - onepassword.com
    resources:
      - "onepassworditems"
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: onepassword-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - onepassword.com
    resources:
      - "onepassworditems"
    verbs: ["get", "list", "watch"]
