# https://github.com/traefik/traefik-helm-chart/releases
.PHONY: localize-crds
localize-crds:
	kustomize localize "https://github.com/traefik/traefik-helm-chart//traefik/crds?ref=v37.1.1" crds # Traefik v3.5.2
