# https://github.com/traefik/traefik-helm-chart/releases
.PHONY: localize-crds
localize-crds:
	kustomize localize "https://github.com/traefik/traefik-helm-chart//traefik/crds?ref=v39.0.8" crds # Traefik v3.6.13
