apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "monitor-ssh-connections"
  annotations:
    description: >
      Track accepted SSH connections
spec:
  kprobes:
    # Inbound Audit: Track accepted SSH connections (Session Start)
    - call: "inet_csk_accept"
      syscall: false
      return: true
      args:
        - index: 0
          type: "sock"
      returnArg:
        index: 0
        type: sock
      selectors:
        - matchArgs:
            - index: 0
              operator: "SPort"
              values:
                - "22"

    # Inbound Audit: Watch for the SSH socket to be closed (Session End)
    - call: "tcp_close"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "SPort"
              values:
                - "22"
