apiVersion: apps/v1
kind: Deployment
metadata:
  name: arc-gha-rs-controller
  namespace: sys-actions
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      nodeSelector:
        node.uw.systems/with-stepsecurity-harden-runner: "true"
      tolerations:
        - key: "node.uw.systems/with-stepsecurity-harden-runner"
          effect: "NoSchedule"
