apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policies/ebpf.yaml
  - policies/fileless-memfd-create.yaml
  - policies/kernel-modules.yaml
  - policies/packet-socket-creation.yaml
  - policies/privileges-raise.yaml
  - policies/ptrace-activity.yaml
  - policies/sensitive-file-access.yaml
  - policies/sensitive-file-links.yaml
  - policies/ssh-connections.yaml
  - policies/ssh-non-standard-port.yaml

patches:
  - path: tetragon-config-patch.yaml
