crds:
  installMethod: "helm"

# hooks are required to map the new container ID to its namespace/labels,
# and push that info down into its eBPF maps *synchronously*.
# since our policies are audit only API Server's asynchronous calls are fine
# rthooks:
#   # -- Enable the Tetragon rthooks daemonset
#   enabled: true
#   interface: nri-hook
#   failAllowNamespacesRegex: [".*"]

tetragon:
  processAncestors:
    enabled: "base,kprobe,tracepoint,lsm"
