crds:
  installMethod: "helm"
rthooks:
  # -- Enable the Tetragon rthooks daemonset
  enabled: true
  interface: nri-hook
  failAllowNamespacesRegex: [".*"]

tetragon:
  processAncestors:
    enabled: "base,kprobe,tracepoint,lsm"
