apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/external-dns/kustomize?ref=c832a23a733106ee5f250a30d5d526572792bcae # v0.21.0

patches:
  - path: patches/deploy.yaml
