apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upstream/apps.yaml
  - upstream/configMaps.yaml
  - upstream/netpols.yaml
  - upstream/rbac.yaml
  - upstream/secrets.yaml