---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trident-node-linux
  labels:
    app: node.csi.trident.netapp.io
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["trident.netapp.io"]
    resources: ["tridentvolumepublications", "tridentbackends", "tridentautogrowpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["trident.netapp.io"]
    resources: ["tridentautogrowrequestinternals"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["trident.netapp.io"]
    resources: ["tridentvolumemoves", "tridentvolumemoves/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
