env:
  customer: "utilitywarehouse"
  apiKey: "step_api_key_change_me"
  clusterName: "[CLUSTER_NAME]"
  arcRunnerNameSpaces:
    - sys-actions
  prometheus:
    enabled: true

nodeSelector:
  node.uw.systems/with-stepsecurity-harden-runner: "true"

tetragon:
  enabled: false
  applyPolicies: true
