runnerScaleSetName: system-exp-merit

listenerTemplate:
  spec:
    nodeSelector:
      node.uw.systems/with-stepsecurity-harden-runner: "true"
    tolerations:
      - key: "node.uw.systems/with-stepsecurity-harden-runner"
        effect: "NoSchedule"
    containers:
      - name: listener

template:
  spec:
    nodeSelector:
      node.uw.systems/with-stepsecurity-harden-runner: "true"
    tolerations:
      - key: "node.uw.systems/with-stepsecurity-harden-runner"
        effect: "NoSchedule"
    containers:
      - name: runner
        image: quay.io/utilitywarehouse/actions-runner:master
        command: ["/home/runner/run.sh"]
        env:
          # Avoid forcing jobs to have a `container` section
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
