# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/configuration-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  creationTimestamp: null
  name: configuration
spec:
  parallel: 1
  fullName: true
  # add required labels to all temp NS created by chainsaw
  namespaceTemplate:
    metadata:
      annotations:
        uw.systems/delete-allowed: "true"
      labels:
        uw.systems/owner: system
